# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'siparis.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(644, 366)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(40, 20, 261, 251))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_kucuk = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_kucuk.setGeometry(QtCore.QRect(40, 70, 112, 23))
        self.radioButton_kucuk.setObjectName("radioButton_kucuk")
        self.radioButton_orta = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_orta.setGeometry(QtCore.QRect(40, 130, 112, 23))
        self.radioButton_orta.setObjectName("radioButton_orta")
        self.radioButton_buyuk = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_buyuk.setGeometry(QtCore.QRect(40, 190, 112, 23))
        self.radioButton_buyuk.setObjectName("radioButton_buyuk")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(340, 20, 261, 251))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_su = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_su.setGeometry(QtCore.QRect(50, 60, 112, 23))
        self.radioButton_su.setObjectName("radioButton_su")
        self.radioButton_ayran = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_ayran.setGeometry(QtCore.QRect(50, 120, 112, 23))
        self.radioButton_ayran.setObjectName("radioButton_ayran")
        self.radioButton_kola = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_kola.setGeometry(QtCore.QRect(50, 180, 112, 23))
        self.radioButton_kola.setObjectName("radioButton_kola")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(260, 300, 121, 51))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Menü"))
        self.radioButton_kucuk.setText(_translate("Form", "Küçük"))
        self.radioButton_orta.setText(_translate("Form", "Orta"))
        self.radioButton_buyuk.setText(_translate("Form", "Büyük"))
        self.groupBox_2.setTitle(_translate("Form", "İçecek"))
        self.radioButton_su.setText(_translate("Form", "Su"))
        self.radioButton_ayran.setText(_translate("Form", "Ayran"))
        self.radioButton_kola.setText(_translate("Form", "Kola"))
        self.pushButton.setText(_translate("Form", "Sipariş Ver"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
